### PR TITLE
chore: Uses CSS Modules to `ImageGallery`

### PR DESCRIPTION
**Pull request by danzanzini**
## What's the purpose of this pull request?

This PR brings the changes made at https://github.com/vtex-sites/nextjs.store/pull/6.
Most specifically, these 2 commits, regarding [CSS modules](https://github.com/vtex-sites/nextjs.store/pull/6/commits/cbef7a810491eb2958a876a97125f8f0be47c1f4) and [grid fixing](https://github.com/vtex-sites/nextjs.store/pull/6/commits/3bfabe49d00699c4955da5b081d788f41a15ead0).

I haven't seen any warning, but I may be looking at the wrong place. @eduardoformiga can you check it, please?

## How does it work?

It moves the import of the CSS file from the `pdp.scss` to the ImageGallery Component. We're doing this to match the way we implement it on the nextjs.store

## How to test it?

Just go to the preview on the magic mouse product and see if it's working.

## References

<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>

<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>

## Checklist

<em>You may erase this after checking them all ;)</em>

- [x] Added an entry in the `CHANGELOG.md` at the beginning of its due section. [The latest version should comes first](https://keepachangelog.com/en/1.0.0/#:~:text=The%20latest%20version%20comes%20first.).
- [x] Added the PR number with the PR link at the entry in the `CHANGELOG.md`. E.g., *New items in the `pull_request_template.md` ([#12](https://github.com/vtex-sites/gatsby.store/pull/12))* 

- PR description
- [x] Added a label according to the PR goal - `Breaking change`, `Enhancement`, `Bug` or `Chore`.
- [x] Added the component, hook, or pathname in-between backticks (``) *- If applicable*. E.g., *`ComponentName` component*.
- [x] Identified the function or parameter in the PR *- If applicable*. E.g., *`useWindowDimensions` hook*.

### CODE REVIEW

**Review by heitorado — APPROVED** [review]
LGTM!

**Comment by hellofanny** [comment]
I'm not sure which behavior is the right one. But I've tried on mobile (IOS / Safari 15) and it seems different from the one on nextJS. (Same thing happened on Chrome)

|[NextJS](https://nextjs.vtex.app/)|[Gatsby Preview](https://preview-41--gatsby.preview.vtex.app/apple-magic-mouse-99988212/p)|
|-|-|
NextJS-gallery|GatsbytJS-gallery|

The NextJS version seems more problematic. The arrows are not disappearing, and I can't reach the last image.

**Comment by danzanzini** [comment]
@hellofanny This will also be solved at nextjs.store with @heitorado work at #27

**Review by eduardoformiga — COMMENTED** [review]
LGTM! 👏 

the problem with the grid and the selectors were fixed!

**Pull request merged**
